#ifndef DEFS_H
#define DEFS_H


#define RADIO_VOX 15
#define MAIN_SENSOR_PIN 16
#define BATTERY_VOLTS_PIN 17

#define NUM_BATT_SAMPLES 100
#define NUM_CYCLES_B4_REPORT 10

#define DISABLE_TIMER()	REG_TC4_CTRLA &= ~TC_CTRLA_ENABLE; \
						while (TC4->COUNT16.STATUS.bit.SYNCBUSY);

#define ENABLE_TIMER() 	REG_TC4_CTRLA |= TC_CTRLA_ENABLE; \
						while (TC4->COUNT16.STATUS.bit.SYNCBUSY);

#define DISABLE_ADC()	REG_ADC_CTRLA &= ~ADC_CTRLA_ENABLE; \
						while (ADC->STATUS.bit.SYNCBUSY);

#define ENABLE_ADC()	REG_ADC_CTRLA |= ADC_CTRLA_ENABLE; \
						while (ADC->STATUS.bit.SYNCBUSY);


#endif